batch_size: 32
cache_dir: cache
download_nltk: true
fusion_method: concat
fusion_output_dim: 64
fusion_weights: null
matching_method: cosine
matching_threshold: 0.3
network_embedding_dim: 64
network_method: node2vec
normalize_temporal: true
num_day_bins: 7
num_time_bins: 24
num_walks: 200
p: 1.0
q: 1.0
semantic_model_name: sentence-transformers/all-MiniLM-L6-v2
tfidf_max_df: 1.0
tfidf_max_features: 5000
tfidf_min_df: 1
timezone: UTC
use_compression: true
use_fallback_embedder: true
use_plotly: true
use_sentence_transformer: true
walk_length: 30
